artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: knkarthick/samsum
  splits:
    train: train
    validation: validation
    test: test
  save_local: true   # Optional: if you want to save locally for caching or inspection

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.json", "test.json", "validation.json"]
